### ISSUE TITLE
Inconsistent group rendering between Context and Container diagrams

### ISSUE THREAD

**Issue by mstine** [goto1134/structurizr-d2-exporter#12]
Hi there-

I'm working on a project using the Structurizr DSL and D2. I've found your project invaluable!

I'm struggling currently with a rendering issue, and I can't seem to track it down by stepping through the debugger. I have, however, figured out what resulting D2 output would resolve my issue.

First, I've created a reproducer project here: https://github.com/mstine/d2-structurizr-containers-with-groups

Second, I'm working with a model where relationships are primarily expressed at the Container level. These Containers all live within a single "Line of Business", which is modeled with the Structurizr Group concept. They often express dependencies on Software Systems that live in other Lines of Business.

Example (from https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/dsl/workspace.dsl): 

```
workspace {
    model {
        group "Line of Business C" {
            ss_c = softwareSystem "System C" {
            }
        }
        group "Line of Business B" {
            ss_b = softwareSystem "System B" {
            }
        }
        group "Line of Business A" {
            ss_a = softwareSystem "System A" {
                c1 = container "Container A1" {
                   -> ss_b "Uses" "HTTP"
                   -> ss_c "Uses" "HTTP"
                }
            }
        }
    }
    views {
        systemContext ss_a "ss_a_Context" "Software System A - Context" {
            include *
        }
        container ss_a "ss_a_Containers" "Software System A - Containers" {
            include *
        }
        styles {
            element "Group:Line of Business A" {
                background "#B0D4CA"
            }
            element "Group:Line of Business B" {
                background "#AA8C65"
            }
            element "Group:Line of Business C" {
                background "#577E7D"
            }
        }
    }
}
```

Executing the simple Kotlin program found at https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/dsl/workspace.dsl produces the D2 output found in:

- https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/d2/ss_a_Context.d2
- https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/d2/ss_a_Containers.d2

I've used the following command lines:

```
$ d2 --layout tala --theme 4 ss_a_Context.d2 
$ d2 --layout tala --theme 4 ss_a_Containers.d2 
```

To produce these SVGs:

- https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/d2/ss_a_Context.svg
- https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/d2/ss_a_Containers.svg

There are two key differences in how the Container diagram is rendered as compared to the Context diagram:

- Group names are rendered as "group_<Group Name>" rather than "<Group Name>".
- Styles are not applied to groups.

I've found that this can be remedied by manually pasting the following snippet into the D2 Container file, which was itself copied from the D2 Context file:

```
"group_Line of Business C": {
  label: "Line of Business C"
  shape: rectangle
  style: {
    fill: "#577e7d"
    font-color: "#cccccc"
    font-size: 24
    opacity: 1.0
    stroke: "#cccccc"
    stroke-dash: 5
    stroke-width: 2
  }
}
"group_Line of Business B": {
  label: "Line of Business B"
  shape: rectangle
  style: {
    fill: "#aa8c65"
    font-color: "#cccccc"
    font-size: 24
    opacity: 1.0
    stroke: "#cccccc"
    stroke-dash: 5
    stroke-width: 2
  }
}
```

Resulting in the following SVG, which is rendered consistently with the Context diagram now: https://github.com/mstine/d2-structurizr-containers-with-groups/blob/main/d2/ss_a_ContainersManualFix.svg.

I've spent a bit of time trying to figure out why these group definitions aren't being written out in Container diagram files, but I need to move on to other things. Can you assist? Thanks!

**Comment by goto1134** [comment]
Hi and thank you for the report. This is an issue in the library indeed!

I tried rendering the container diagram with both Plantuml and structurizr cloud. In both cases the software systems do not have any groups at all. Here are the examples:
![image](https://github.com/goto1134/structurizr-d2-exporter/assets/9569795/c5cbee38-b537-48f0-a7c8-c8f0488d69fd)
![image](https://github.com/goto1134/structurizr-d2-exporter/assets/9569795/0c936393-e3c3-42fa-b1a1-298bf3716918)

The goal of this project is to be as close to the structurizr spec as possible. Therefore I will remove the groups for the software systems in the container diagrams.

The result will look like this:
![d2](https://github.com/goto1134/structurizr-d2-exporter/assets/9569795/d93d40b5-433e-4649-a403-5013e808d616)
