### ISSUE TITLE
Workspace Positions

### ISSUE THREAD

**Issue by hwinkel** [goto1134/structurizr-d2-exporter#14]
Hi, does the D2 Exporter support the Workspace Setting (JSON) for the positioning of the Elements to maintain alignment?

**Comment by goto1134** [comment]
Hi, @hwinkel. I haven't tested that. Do you have an example? 

It would help if you could provide a short listing in structurizr with your preferred visualization

**Comment by hwinkel** [comment]
Thanks, will do next days.

**Comment by simonbrowndotje** [comment]
I think @hwinkel is asking whether you can specify element x,y coordinates in a D2 export ... i.e. manual layout rather than using dagre/ELK/TALA.

**Comment by goto1134** [comment]
As I read in the d2 documentation, all you can do is specify the relative positions for the elements, not coordinates.

> In general, positioning is controlled entirely by the layout engine. It's one of the primary benefits of text-to-diagram that you don't have to manually define all the positions of objects.
> https://d2lang.com/tour/positions

**Comment by goto1134** [comment]
If you still would like to control position relative to other elements, we could support custom properties for that like it is done for title position here (https://github.com/goto1134/structurizr-d2-exporter/blob/main/README.md).

Otherwise, please, file an issue to https://github.com/terrastruct/d2

**Comment by hwinkel** [comment]
Hhm , at least from terrastuct web editor I remember that they also have stored positions in the model, but I see the latest architect version dropped the support. It might be not part of the d2 language but part of the tool it seems. Just like it is within structurizr UI.
